version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root12345
      MYSQL_DATABASE: gptanalytics
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  api:
    build: ./
    volumes:
      - ./:/app
    links:
      - mysql
    ports:
      - "8080:8080"

volumes:
  mysql_data:
